### ISSUE TITLE
"Files added to null/2go.zip" after selecting Downloads folder in Android 9

### ISSUE THREAD

**Issue by nicolas-raoul** [k3b/ToGoZip#23]
The resulting file is `2go.zip.tmp.zip` and its filesize is zero byte.

Samsung S10
Android 9

**Comment by k3b** [comment]
thanks for the error report.

what is the full output path?

i had err #20 where some (but not all) android-7.0 forbids writing to root directory.

since i donot have a device with android-9: are there other 3rd-party apps (beside samsung-system apps) that allow to write to the selected output folder?

I assume that bug-report #22 is the same as #23 so that i can close #22 as duplicate?

**Comment by k3b** [comment]
does the error still exist with the last release where i added checks for root directory (#20) Can i close this ticket?

**Comment by nicolas-raoul** [comment]
Sorry I haven't tried in a while, I guess this can be closed, thanks! :-)
